apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaces
  namespace: spaces
  labels:
    app.kubernetes.io/name: spaces
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: spaces
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spaces
    spec:
      containers:
        - name: spaces
          image: ghcr.io/ndaden/spaces:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
