apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spaces
  namespace: spaces
  labels:
    app.kubernetes.io/name: spaces
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - spaces.dnabil.ovh
      secretName: spaces-tls
  rules:
    - host: spaces.dnabil.ovh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spaces
                port:
                  number: 80
